version: '3.7'

services:
  drupal:
    image: drupal:10
    ports:
      - "8080:80"
    volumes:
      - ./web:/opt/drupal/web
      - ./modules:/opt/drupal/web/modules
      - ./themes:/opt/drupal/web/themes
      - ./profiles:/opt/drupal/web/profiles
      - ./sites:/opt/drupal/web/sites
      - ./config:/opt/drupal/config
      - ./vendor:/opt/drupal/vendor
      - ./private:/opt/drupal/private
      - ./composer.json:/opt/drupal/composer.json
      - ./composer.lock:/opt/drupal/composer.lock
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
